#!/bin/bash
cp -r index.html main.css images/ Free\ App/;
cp -r scripts/c*.js scripts/jquery.min.js Free\ App/scripts;
zip -ru Free\ App.zip Free\ App/
cp -r paid.html main.css images/ Paid\ App/;
cp -r scripts/c*.js scripts/p*.js scripts/jquery.min.js Paid\ App/scripts;
zip -ru Paid\ App.zip Paid\ App/
