#!/bin/bash
java -jar compiler.jar --js vars.js --compilation_level SIMPLE_OPTIMIZATIONS --js_output_file ../../../Compiled/scripts/cvars.js;
java -jar compiler.jar --js engine.js --compilation_level SIMPLE_OPTIMIZATIONS --js_output_file ../../../Compiled/scripts/cengine.js;
java -jar compiler.jar --js game.js --compilation_level SIMPLE_OPTIMIZATIONS --js_output_file ../../../Compiled/scripts/cgame.js;
java -jar compiler.jar --js levels.js --compilation_level SIMPLE_OPTIMIZATIONS --js_output_file ../../../Compiled/scripts/clevels.js
