#!/bin/bash
cp -r ../Source/Source/index.html ../Source/Source/main.css ../Source/Source/images/ ../Source/Source/fonts/ ../Chrome/Free\ App/;
cp -r ../Web\ App/scripts/c*.js ../Chrome/Free\ App/scripts;
rm ../Chrome/Free\ App.zip;
cd ../Chrome;
zip -r Free\ App.zip Free\ App/;
