/*
 Copyright 2011 Steven Holms <superlinkx@gmail.com>

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
function backgroundDraw(){60==bgpos&&(bgpos=0);ctx.fillStyle=bgcolor;ctx.fillRect(0,0,w,h);ctx.beginPath();ctx.strokeStyle=bgline;for(i=60;i<=w;i+=60)ctx.moveTo(i,0),ctx.lineTo(i,h);for(i=bgpos;i<=h;i+=60)ctx.moveTo(0,i),ctx.lineTo(w,i);ctx.stroke();bgpos+=1}function Player(a,b){this.x=a;this.y=b;this.h=this.w=30}function playerDraw(){rightKey&&(player.x+=5);leftKey&&(player.x-=5);upKey&&(player.y-=5);downKey&&(player.y+=5);playerBounds();ctx.drawImage(pSprite,player.x,player.y)}
function playerBounds(){if(player.x>w-31)player.x=w-30;if(1>player.x)player.x=0;if(player.y>h-31)player.y=h-30;if(1>player.y)player.y=0}function shipCollision(){for(var a=0;a<enemies.length;a++)if(player.x>=enemies[a].x&&player.x<=enemies[a].x+enemies[a].w||player.x+player.w>=enemies[a].x&&player.x+player.w<=enemies[a].x+enemies[a].w)(player.y>=enemies[a].y&&player.y<=enemies[a].y+enemies[a].h||player.y+player.h>=enemies[a].y&&player.y+player.h<=enemies[a].y+enemies[a].h)&&checkLives()}
function Enemy(a,b,c,d,e,f,g){this.x=a;this.y=b;this.w=c;this.h=d;this.speed=e;this.initx=f;this.type=g;this.fired=0}function drawEnemy(){for(var a=0;a<enemies.length;a++)switch(enemies[a].type){case 1:ctx.drawImage(e1Sprite,enemies[a].x,enemies[a].y);break;case 2:ctx.drawImage(e2Sprite,enemies[a].x,enemies[a].y);break;default:ctx.drawImage(e1Sprite,enemies[a].x,enemies[a].y)}}
function enemyFire(){for(var a=0;a<enemies.length;a++)switch(enemies[a].type){case 2:if(!enemies[a].fired)enemyLasers.push(new Laser(enemies[a].x+(enemies[a].w/2-laserWidth/2),enemies[a].y,laserWidth,20)),enemies[a].fired=1}}
function drawEnemyLaser(){if(enemyLasers.length)for(var a=0;a<enemyLasers.length;a++){var b=ctx.createLinearGradient(enemyLasers[a].x,enemyLasers[a].y,enemyLasers[a].x,enemyLasers[a].y+20);b.addColorStop(0,"rgba(255,0,0,0.2)");b.addColorStop(1,"rgba(255,0,0,0.8)");ctx.fillStyle=b;ctx.fillRect(enemyLasers[a].x,enemyLasers[a].y,enemyLasers[a].w,enemyLasers[a].h)}}function moveEnemyLaser(){for(var a=0;a<enemyLasers.length;a++)enemyLasers[a].y+=10,810<enemyLasers[a].y&&enemyLasers.splice(a,1)}
function randomType(){var a=Math.ceil(2*Math.random());0==a&&(a=1);return a}function typeSpeed(a){switch(a){case 1:return enemy1Speed;case 2:return enemy2Speed;default:return enemy1Speed}}function randomPath(){return Math.ceil(20*Math.random())}
function currentPath(a){switch(a){case 1:pathSize=w/20;break;case 2:pathSize=2*(w/20);break;case 3:pathSize=3*(w/20);break;case 4:pathSize=4*(w/20);break;case 5:pathSize=5*(w/20);break;case 6:pathSize=6*(w/20);break;case 7:pathSize=7*(w/20);break;case 8:pathSize=8*(w/20);break;case 9:pathSize=9*(w/20);break;case 10:pathSize=10*(w/20);break;case 11:pathSize=11*(w/20);break;case 12:pathSize=12*(w/20);break;case 13:pathSize=13*(w/20);break;case 14:pathSize=14*(w/20);break;case 15:pathSize=15*(w/20);
break;case 16:pathSize=16*(w/20);break;case 17:pathSize=17*(w/20);break;case 18:pathSize=18*(w/20);break;case 19:pathSize=19*(w/20);break;case 20:pathSize=20*(w/20);break;default:return err}return pathSize}
function moveEnemy(){for(var a=0;a<enemies.length;a++)switch(enemies[a].type){case 1:enemies[a].x=e1xa*Math.sin(e1xf*enemies[a].y)+enemies[a].initx;if(enemies[a].y<h)enemies[a].y+=enemies[a].speed;else if(enemies[a].y>h-1)enemies[a].y=-45;break;case 2:if(enemies[a].y<h)enemies[a].y+=enemies[a].speed;else if(enemies[a].y>h-1)enemies[a].y=-45;break;default:if(enemies[a].x=e1xa*Math.sin(e1xf*enemies[a].y)+enemies[a].initx,enemies[a].y<h)enemies[a].y+=enemies[a].speed;else if(enemies[a].y>h-1)enemies[a].y=
-45}}function enemyLaserTest(){for(var a=!1,b=0;b<enemyLasers.length;b++){if((enemyLasers[b].x>=player.x&&enemyLasers[b].x<=player.x+player.w||enemyLasers[b].x+enemyLasers[b].w>=player.x&&enemyLasers[b].x+enemyLasers[b].w<=player.x+player.w)&&enemyLasers[b].y>=player.y&&enemyLasers[b].y<=player.y+player.h)a=!0,checkLives();!0==a&&(enemyLasers.splice(b,1),a=!1)}}
function hitTest(){for(var a=!1,b=0;b<lasers.length;b++){for(var c=0;c<enemies.length;c++)if((lasers[b].x>=enemies[c].x&&lasers[b].x<=enemies[c].x+enemies[c].w||lasers[b].x+lasers[b].w>=enemies[c].x&&lasers[b].x+lasers[b].w<=enemies[c].x+enemies[c].w)&&lasers[b].y>=enemies[c].y&&lasers[b].y<=enemies[c].y+enemies[c].h){enemyKilled+=1;a=!0;enemies.splice(c,1);sc0re+=10*sc0reMult;path=randomPath();e1x=currentPath(path);type=randomType();var d=typeSpeed(type);enemies.push(new Enemy(e1x,-45,e1w,e1h,d,
e1x,type))}!0==a&&(lasers.splice(b,1),a=!1)}}function Laser(a,b,c,d){this.x=a;this.y=b;this.w=c;this.h=d}function drawLaser(){if(lasers.length)for(var a=0;a<lasers.length;a++){var b=ctx.createLinearGradient(lasers[a].x,lasers[a].y,lasers[a].x,lasers[a].y+20);b.addColorStop(0,"rgba(255,0,0,0.8)");b.addColorStop(1,"rgba(255,0,0,0.2)");ctx.fillStyle=b;ctx.fillRect(lasers[a].x,lasers[a].y,lasers[a].w,lasers[a].h)}}
function laserFire(){!0==laserKey&&5<=laserTime&&0<laserCount&&(lasers.push(new Laser(player.x+(player.w/2-laserWidth/2),player.y,laserWidth,20)),laserTime=0,laserCount--);laserTime+=1;laserCount<laserLimit&&!(laserFireTracker++%laserTimeout)&&laserCount++}function moveLaser(){for(var a=0;a<lasers.length;a++)-11<lasers[a].y?lasers[a].y-=10:-10>lasers[a].y&&lasers.splice(a,1)}function checkLives(){lives-=1;reset();0==lives&&(alive=!1)}
function reset(){storageCalled=!1;lasers.splice(0,lasers.length);enemyLasers.splice(0,lasers.length);laserFireTracker=enemyLasers.length=0;laserCount=4;player.x=w/2-15;player.y=h-30;player.w=30;player.h=30;enemies.splice(0,enemies.length);for(i=0;i<enemyTotal;i++){path=randomPath();e1x=currentPath(path);type=randomType();var a=typeSpeed(type);enemies.push(new Enemy(e1x,-45,e1w,e1h,a,e1x,type))}}
function keyDown(a){a.preventDefault();39==a.keyCode?rightKey=!0:37==a.keyCode&&(leftKey=!0);38==a.keyCode?upKey=!0:40==a.keyCode&&(downKey=!0);32==a.keyCode&&(laserKey=!0);13==a.keyCode&&(enterKey=!0);191==a.keyCode&&pauseGame()}function keyUp(a){a.preventDefault();39==a.keyCode?rightKey=!1:37==a.keyCode&&(leftKey=!1);38==a.keyCode?upKey=!1:40==a.keyCode&&(downKey=!1);32==a.keyCode&&(laserKey=!1);13==a.keyCode&&(enterKey=!1)};
