var b=!0,c=!1;if(!d)var d="";var f=30,g=480,h=800,aa=30,ba=30;x=0;y=0;bgpos=0;px=g/2-15;py=h-30;e1x=25;e1y=-45;bgcolor="rgb(0,0,0)";bgline="rgb(0,255,0)";pSprite=new Image;pSprite.src=d+"images/heliumclass1.png";var j=new Image;j.src=d+"images/enemy1.png";var k=new Image;k.src=d+"images/enemy2.png";var l=c,n=c,o=c,p=c,q=c,r=c,s=[],t=[],u=0,v=3,w=4,z=8,A=null,B=null,C=50,D=2*Math.PI/240,E=[],F=c,G=0,H=4,I=4,ca=4,J=0,da=20,K=0,L=1,M=b,N=3,O=c,P=1,Q=c,R=null,S=null;var ea=new T([3,4,8,1,"rgb(0,0,0)","rgb(0,255,0)"]),fa=new T([4,5,9,1,"rgb(0,0,0)","rgb(0,0,255)"]),ga=new T([5,6,10,1,"rgb(0,0,0)","rgb(255,0,0)"]),ha=new T([6,7,11,1,"rgb(0,0,0)","rgb(0,255,255)"]),ia=new T([7,8,12,1,"rgb(0,0,0)","rgb(255,255,0)"]),ja=new T([8,9,13,1,"rgb(0,0,0)","rgb(255,0,255)"]),ka=new T([9,10,14,1,"rgb(0,0,0)","rgb(255,255,255)"]),la=new T([10,11,15,1,"rgb(255,255,255)","rgb(0,0,0)"]),ma=new T([11,12,16,1,"rgb(255,255,255)","rgb(0,255,0)"]),na=new T([12,13,17,1,"rgb(255,255,255)",
"rgb(255,0,0)"]);function T(a){this.g=a[0];this.h=a[1];this.i=a[2];this.j=a[3];this.e=a[4];this.f=a[5]};/*
 Copyright 2011 Steven Holms <superlinkx@gmail.com>

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
function oa(){this.x=px;this.y=py;this.b=this.a=30}function U(a){var e=aa,m=ba,ra=pa();this.x=e1x;this.y=a;this.a=e;this.b=m;this.speed=ra;this.d=e1x;this.type=type;this.c=0}function V(){var a=Math.ceil(2*Math.random());0==a&&(a=1);return a}function pa(){switch(type){case 1:return v;case 2:return w;default:return v}}
function W(){switch(A){case 1:B=g/20;break;case 2:B=2*(g/20);break;case 3:B=3*(g/20);break;case 4:B=4*(g/20);break;case 5:B=5*(g/20);break;case 6:B=6*(g/20);break;case 7:B=7*(g/20);break;case 8:B=8*(g/20);break;case 9:B=9*(g/20);break;case 10:B=10*(g/20);break;case 11:B=11*(g/20);break;case 12:B=12*(g/20);break;case 13:B=13*(g/20);break;case 14:B=14*(g/20);break;case 15:B=15*(g/20);break;case 16:B=16*(g/20);break;case 17:B=17*(g/20);break;case 18:B=18*(g/20);break;case 19:B=19*(g/20);break;case 20:B=
20*(g/20);break;default:return}return B}function X(a,e){var m=H;this.x=a;this.y=e;this.a=m;this.b=20}function Y(){N-=1;Z();0==N&&(M=c)}function Z(){Q=c;E.splice(0,E.length);t.splice(0,E.length);J=t.length=0;I=4;player.x=g/2-15;player.y=h-30;player.a=30;player.b=30;s.splice(0,s.length);for(i=0;i<z;i++)A=Math.ceil(20*Math.random()),e1x=W(),type=V(),s.push(new U(-45))}
function qa(a){a.preventDefault();39==a.keyCode?o=b:37==a.keyCode&&(p=b);38==a.keyCode?l=b:40==a.keyCode&&(n=b);32==a.keyCode&&(F=b);13==a.keyCode&&(q=b);if(191==a.keyCode)r?(game=window.setTimeout($,1E3/f),r=c):(window.clearTimeout(game),r=b,S.fillStyle="rgba(255,255,255,0.7)",S.fillRect(0,0,g,h),S.fillStyle="#f00",S.font='54px "Times New Roman"',S.fillText("Paused",g/2-70,h/2),S.font='36px "Times New Roman"',S.fillText("Press / to Continue",g/2-130,h/2+60))}
function sa(a){a.preventDefault();39==a.keyCode?o=c:37==a.keyCode&&(p=c);38==a.keyCode?l=c:40==a.keyCode&&(n=c);32==a.keyCode&&(F=c);13==a.keyCode&&(q=c)};function ta(){O=b;Z();R.removeEventListener("click",ta,c)};function $(){S.clearRect(0,0,g,h);60==bgpos&&(bgpos=0);S.fillStyle=bgcolor;S.fillRect(0,0,g,h);S.beginPath();S.strokeStyle=bgline;for(i=60;i<=g;i+=60)S.moveTo(i,0),S.lineTo(i,h);for(i=bgpos;i<=h;i+=60)S.moveTo(0,i),S.lineTo(g,i);S.stroke();bgpos+=1;q&&ta();if(!O)S.fillStyle="rgba(255,255,255,0.7)",S.fillRect(0,0,g,h),S.fillStyle="#f00",S.font='54px "Times New Roman"',S.fillText("Project Helium",g/2-160,h/2),S.font='36px "Times New Roman"',S.fillText("Press Enter to Play",g/2-130,h/2+50),S.fillText("Use arrow keys to move",
g/2-175,h/2+90),S.fillText("Use space to shoot",g/2-130,h/2+130);if(M&&O&&0<N){switch(u){case 0:P=1;break;case 100:P=2;break;case 200:P=3;break;case 300:P=4;break;case 400:P=5;break;case 500:P=6;break;case 600:P=7;break;case 700:P=8;break;case 800:P=9;break;case 900:P=10}switch(P){case 1:currentLevel=ea;break;case 2:currentLevel=fa;break;case 3:currentLevel=ga;break;case 4:currentLevel=ha;break;case 5:currentLevel=ia;break;case 6:currentLevel=ja;break;case 7:currentLevel=ka;break;case 8:currentLevel=
la;break;case 9:currentLevel=ma;break;case 10:currentLevel=na}v=currentLevel.g;w=currentLevel.h;z=currentLevel.i;L=currentLevel.j;bgcolor=currentLevel.e;bgline=currentLevel.f;for(var a=0;a<s.length;a++)switch(s[a].type){case 1:s[a].x=C*Math.sin(D*s[a].y)+s[a].d;if(s[a].y<h)s[a].y+=s[a].speed;else if(s[a].y>h-1)s[a].y=-45;break;case 2:if(s[a].y<h)s[a].y+=s[a].speed;else if(s[a].y>h-1)s[a].y=-45;break;default:if(s[a].x=C*Math.sin(D*s[a].y)+s[a].d,s[a].y<h)s[a].y+=s[a].speed;else if(s[a].y>h-1)s[a].y=
-45}for(a=0;a<E.length;a++)-11<E[a].y?E[a].y-=10:-10>E[a].y&&E.splice(a,1);for(a=0;a<t.length;a++)t[a].y+=10,810<t[a].y&&t.splice(a,1);for(a=0;a<s.length;a++)switch(s[a].type){case 1:S.drawImage(j,s[a].x,s[a].y);break;case 2:S.drawImage(k,s[a].x,s[a].y);break;default:S.drawImage(j,s[a].x,s[a].y)}F==b&&5<=G&&0<I&&(E.push(new X(player.x+(player.a/2-H/2),player.y)),G=0,I--);G+=1;I<ca&&!(J++%da)&&I++;if(E.length)for(a=0;a<E.length;a++){var e=S.createLinearGradient(E[a].x,E[a].y,E[a].x,E[a].y+20);e.addColorStop(0,
"rgba(255,0,0,0.8)");e.addColorStop(1,"rgba(255,0,0,0.2)");S.fillStyle=e;S.fillRect(E[a].x,E[a].y,E[a].a,E[a].b)}for(a=0;a<s.length;a++)switch(s[a].type){case 2:if(!s[a].c)t.push(new X(s[a].x+(s[a].a/2-H/2),s[a].y)),s[a].c=1}if(t.length)for(a=0;a<t.length;a++)e=S.createLinearGradient(t[a].x,t[a].y,t[a].x,t[a].y+20),e.addColorStop(0,"rgba(255,0,0,0.2)"),e.addColorStop(1,"rgba(255,0,0,0.8)"),S.fillStyle=e,S.fillRect(t[a].x,t[a].y,t[a].a,t[a].b);o&&(player.x+=5);p&&(player.x-=5);l&&(player.y-=5);n&&
(player.y+=5);if(player.x>g-31)player.x=g-30;if(1>player.x)player.x=0;if(player.y>h-31)player.y=h-30;if(1>player.y)player.y=0;S.drawImage(pSprite,player.x,player.y);a=c;for(e=0;e<E.length;e++){for(var m=0;m<s.length;m++)if((E[e].x>=s[m].x&&E[e].x<=s[m].x+s[m].a||E[e].x+E[e].a>=s[m].x&&E[e].x+E[e].a<=s[m].x+s[m].a)&&E[e].y>=s[m].y&&E[e].y<=s[m].y+s[m].b)u+=1,a=b,s.splice(m,1),K+=10*L,A=Math.ceil(20*Math.random()),e1x=W(),type=V(),s.push(new U(-45));a==b&&(E.splice(e,1),a=c)}a=c;for(e=0;e<t.length;e++){if((t[e].x>=
player.x&&t[e].x<=player.x+player.a||t[e].x+t[e].a>=player.x&&t[e].x+t[e].a<=player.x+player.a)&&t[e].y>=player.y&&t[e].y<=player.y+player.b)a=b,Y();a==b&&(t.splice(e,1),a=c)}for(a=0;a<s.length;a++)if(player.x>=s[a].x&&player.x<=s[a].x+s[a].a||player.x+player.a>=s[a].x&&player.x+player.a<=s[a].x+s[a].a)(player.y>=s[a].y&&player.y<=s[a].y+s[a].b||player.y+player.b>=s[a].y&&player.y+player.b<=s[a].y+s[a].b)&&Y()}if(!M){N=0;S.fillStyle="rgba(255,255,255,0.7)";S.fillRect(0,0,g,h);S.fillStyle="#f00";S.fillText("Game Over!",
g/2-63,h/2);S.fillText("Press Enter to Continue...",g/2-133,h/2+80);if(!Q)localStorage.topScore?parseInt(parseFloat(localStorage.topScore))<K&&(localStorage.topScore=K):localStorage.topScore=K,localStorage.lastScore=K,a=document.getElementById("lastScore"),document.getElementById("topScore").innerHTML="Your Highest Score Ever Was: "+localStorage.topScore,a.innerHTML="Your Latest Score Was: "+localStorage.lastScore,Q=b;q&&(M=b,N=3,u=K=0,v=3,w=4,Z())}S.font='26px "Times New Roman"';S.fillStyle="rgba(255,255,255,0.8)";
S.fillRect(0,0,g,60);S.fillStyle="#f00";S.fillText("Score: ",10,55);S.fillText(K,170,55);S.fillText("Lives:",10,20);S.fillText(N,170,20);S.fillText("Level:",g-170,20);10>P&&S.fillText(P,g-20,20);10<=P&&S.fillText(P,g-30,20);S.fillText("Shots:",g-170,55);S.fillText(I,g-20,55);game=window.setTimeout("gameLoop()",1E3/f)}
window.onload=function(){R=document.getElementById("helium");S=R.getContext("2d");R.width=g;R.height=h;R.addEventListener("keydown",qa,c);R.addEventListener("keyup",sa,c);var a=document.getElementById("topScore"),e=document.getElementById("lastScore");if(localStorage.topScore)a.innerHTML="Your Highest Score Ever Was: "+localStorage.topScore;if(localStorage.lastScore)e.innerHTML="Your Latest Score Was: "+localStorage.lastScore;for(a=0;a<z;a++)A=Math.ceil(20*Math.random()),e1x=W(),type=V(),s.push(new U(e1y));
player=new oa;$()};
